// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvia.Provider.Arithmetic.Runtime")>]
[<assembly: AssemblyProductAttribute("Sylvia")>]
[<assembly: AssemblyDescriptionAttribute("Run-time assembly for the Sylvia.Arithmetic type provider.")>]
[<assembly: AssemblyVersionAttribute("0.2.5.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.5.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvia.Provider.Arithmetic.Runtime"
    let [<Literal>] AssemblyProduct = "Sylvia"
    let [<Literal>] AssemblyDescription = "Run-time assembly for the Sylvia.Arithmetic type provider."
    let [<Literal>] AssemblyVersion = "0.2.5.1"
    let [<Literal>] AssemblyFileVersion = "0.2.5.1"
