// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvia.Provider.Arithmetic.DesignTime")>]
[<assembly: AssemblyProductAttribute("Sylvia")>]
[<assembly: AssemblyDescriptionAttribute("Design-time assembly for the Sylvia.Arithmetic type provider.")>]
[<assembly: AssemblyVersionAttribute("0.2.8.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.8.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvia.Provider.Arithmetic.DesignTime"
    let [<Literal>] AssemblyProduct = "Sylvia"
    let [<Literal>] AssemblyDescription = "Design-time assembly for the Sylvia.Arithmetic type provider."
    let [<Literal>] AssemblyVersion = "0.2.8.0"
    let [<Literal>] AssemblyFileVersion = "0.2.8.0"
